In [1]:
import requests
import pandas as pd
from pandas.io.json import json_normalize
from datetime import datetime

In [2]:
data = requests.get("https://data.sfgov.org/resource/jjew-r69b.json")
df = json_normalize(data.json())
df.dtypes

dayorder                  object
dayofweekstr              object
starttime                 object
endtime                   object
permit                    object
location                  object
locationdesc              object
optionaltext              object
locationid                object
start24                   object
end24                     object
cnn                       object
addr_date_create          object
addr_date_modified        object
block                     object
lot                       object
coldtruck                 object
applicant                 object
x                         object
y                         object
latitude                  object
longitude                 object
location_2.type           object
location_2.coordinates    object
dtype: object

In [3]:
df.head()

,dayorder,dayofweekstr,starttime,endtime,permit,location,locationdesc,optionaltext,locationid,start24,...,block,lot,coldtruck,applicant,x,y,latitude,longitude,location_2.type,location_2.coordinates
0,2,Tuesday,6AM,11PM,19MFF-00127,1 MONTGOMERY ST,"On the north side of Post Street, in the first...",Prepackaged Kettlecorn,1382718,06:00,...,0292,002,N,Treats by the Bay LLC,6012069.59783,2115384.37093,37.789121900046254,-122.40207154934198,Point,"[-122.402071549342, 37.7891219000463]"
1,3,Wednesday,6AM,11PM,19MFF-00127,1 MONTGOMERY ST,"On the north side of Post Street, in the first...",Prepackaged Kettlecorn,1382718,06:00,...,0292,002,N,Treats by the Bay LLC,6012069.59783,2115384.37093,37.789121900046254,-122.40207154934198,Point,"[-122.402071549342, 37.7891219000463]"
2,4,Thursday,6AM,11PM,19MFF-00127,1 MONTGOMERY ST,"On the north side of Post Street, in the first...",Prepackaged Kettlecorn,1382718,06:00,...,0292,002,N,Treats by the Bay LLC,6012069.59783,2115384.37093,37.789121900046254,-122.40207154934198,Point,"[-122.402071549342, 37.7891219000463]"
3,2,Tuesday,10AM,6PM,19MFF-00105,773 MARKET ST,Pushcart located on Market St. 7 linear feet W...,"Kettle Corn, Funnel Cakes, Lemonade, Beverages...",1341056,10:00,...,3706,096,N,Kettle Corn Star,6011164.82111,2114324.40143,37.786160934428665,-122.40512731130576,Point,"[-122.405127311306, 37.7861609344287]"
4,1,Monday,10AM,6PM,19MFF-00105,773 MARKET ST,Pushcart located on Market St. 7 linear feet W...,"Kettle Corn, Funnel Cakes, Lemonade, Beverages...",1341056,10:00,...,3706,096,N,Kettle Corn Star,6011164.82111,2114324.40143,37.786160934428665,-122.40512731130576,Point,"[-122.405127311306, 37.7861609344287]"

In [4]:
date = datetime.now()
day_of_week = date.strftime('%A')
time = date.strftime('%H:%M')
#offset = 10
print(day_of_week, time)

Wednesday 12:10

In [7]:
#query = "https://data.sfgov.org/resource/jjew-r69b.json?$query=SELECT start24, end24, applicant as name, location as address WHERE dayofweekstr='{day_of_week}' AND '{time}' BETWEEN start24 AND end24 ORDER BY applicant LIMIT 5 OFFSET {offset}".format(day_of_week=day_of_week, time=time, offset=offset)
query = "https://data.sfgov.org/resource/jjew-r69b.json?$query=SELECT start24, end24, applicant as name, location as address WHERE dayofweekstr='{day_of_week}' AND '{time}' BETWEEN start24 AND end24 ORDER BY applicant".format(day_of_week=day_of_week, time=time, offset=offset)
print(query)
data = requests.get(query)
filtered_df = json_normalize(data.json())

https://data.sfgov.org/resource/jjew-r69b.json?$query=SELECT start24, end24, applicant as name, location as address WHERE dayofweekstr='Wednesday' AND '12:10' BETWEEN start24 AND end24 ORDER BY applicant

In [8]:
filtered_df

,start24,end24,name,address
0,12:00,13:00,Anas Goodies Catering,640 TENNESSEE ST
1,12:00,13:00,Anas Goodies Catering,1255 22ND ST
2,12:00,13:00,Anas Goodies Catering,951 INDIANA ST
3,12:00,13:00,Anas Goodies Catering,1082 PENNSYLVANIA AVE
4,12:00,13:00,Anas Goodies Catering,700 PENNSYLVANIA AVE
...,...,...,...,...
195,08:00,15:00,Tres Agaves Mexican Kitchen & Tequila Lounge L...,1700 16TH ST
196,12:00,14:00,Two G's Catering,599 08TH ST
197,09:00,17:00,Wonder Philly,960 04TH ST
198,10:00,15:00,Wu Wei LLC dba MoBowl,75 HOWARD ST
199,10:00,19:00,Yummy Hot Dogs,945 MARKET ST